spring.profiles.active: dev
spring:
  security:
    oauth2:
      client:
        registration:
          vk:
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            client-id: ...
            client-secret: ...
            authorizationGrantType: authorization_code
            scope: email
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
          vk:
            authorizationUri: https://oauth.vk.com/authorize
            tokenUri: https://oauth.vk.com/access_token
            userInfoUri: https://api.vk.com/method/users.get
  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    drop-first: false
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
  #JPA
  jpa:
    show-sql: false
    properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect