spring.profiles.active: dev

spring:
  #JPA
  jpa:
    show-sql: false
    properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    drop-first: false